# This runs cron jobs daily

name: Daily

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  codeql:
    uses: pyiron/actions/.github/workflows/tests-and-coverage.yml@actions-4.0.13
    secrets: inherit
    with:
      extra-python-paths: tests
      tests-env-files: .ci_support/environment.yml .ci_support/environment-pwd.yml
