# This runs jobs which pyiron modules should run on pushes or PRs to main

name: Push-Pull

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pyiron:
    uses: pyiron/actions/.github/workflows/push-pull.yml@actions-4.0.13
    secrets: inherit
    with:
      do-coveralls: false
      do-codecov: true
      # Run mypy, ensuring it has access to pydantic
      do-mypy: true
      tests-env-files: .ci_support/environment.yml .ci_support/environment-optional.yml
      docs-env-files: .ci_support/environment.yml .ci_support/environment-optional.yml
      notebooks-env-files: .ci_support/environment.yml .ci_support/environment-optional.yml .ci_support/environment-notebook.yml
      mypy-env-files: .ci_support/environment.yml .ci_support/environment-optional.yml
      # The test matrix supports up to four python versions
      python-version-alt3: '3.13'
      python-version-alt2: '3.12'
      python-version-alt1: '3.11'
      python-version: '3.14'
      # Test lower bounds:
      alternate-tests-env-files: .ci_support/lower-bounds.yml
      alternate-tests-python-version: '3.11'
      alternate-tests-dir: tests/unit
      # Make sure the static module can be found at test time
      extra-python-paths: tests
      # Don't include the API in coverage
      omit-patterns: '*/flowrep/api/*'

  tests-without-optionals:
    uses: pyiron/actions/.github/workflows/tests-and-coverage.yml@actions-4.0.13
    secrets: inherit
    with:
      tests-env-files: .ci_support/environment.yml
      test-dir: tests/unit
      extra-python-paths: tests
      do-coveralls: false
      do-codecov: false
